services:
  - type: web
    name: blankate-web
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm ci --prefer-offline --no-audit && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: NEXT_PUBLIC_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_COINGECKO_API_KEY
        sync: false
    autoDeploy: true
    branch: main
    rootDir: .
    
    # Scaling configuration
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 70
      targetCPUPercent: 70
      
    # Custom domains (add your domain here)
    # domains:
    #   - blankate.com
    #   - www.blankate.com

# Optional: Database service (uncomment if needed)
# databases:
#   - name: blankate-db
#     databaseName: blankate
#     user: blankate
#     plan: starter
#     region: oregon
